#!/bin/bash
# Forensic Flight worker VM startup script
# GCP runs this on every boot via metadata startup-script key.
# Idempotent: safe to run repeatedly; each section guards itself.
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive

# ── B1: Docker via official Docker apt repository ────────────────────────────
# docker.io from Debian repos does NOT include docker-compose-plugin.
# Must use download.docker.com to get docker-ce + docker-compose-plugin.

if ! command -v docker &>/dev/null; then
  apt-get update -q
  apt-get install -y -q ca-certificates curl gnupg lsb-release

  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/debian/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg

  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list

  apt-get update -q
  apt-get install -y -q \
    docker-ce docker-ce-cli containerd.io docker-compose-plugin

  systemctl enable docker
  systemctl start docker
fi

# ── gcloud SDK ────────────────────────────────────────────────────────────────

if ! command -v gcloud &>/dev/null; then
  curl -fsSL \
    https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz \
    | tar -xz -C /opt
  /opt/google-cloud-sdk/install.sh --quiet --path-update false
  ln -sf /opt/google-cloud-sdk/bin/gcloud /usr/local/bin/gcloud
fi

# ── Instance metadata ─────────────────────────────────────────────────────────

METADATA_URL="http://metadata.google.internal/computeMetadata/v1"

meta() {
  curl -sf -H "Metadata-Flavor: Google" "$METADATA_URL/$1"
}

VM_INTERNAL_IP=$(meta "instance/network-interfaces/0/ip")
PROJECT_ID=$(meta "project/project-id")

# ── B2: Mount Qdrant persistent disk ─────────────────────────────────────────
# device_name="qdrant-data" in Terraform → appears as google-qdrant-data under by-id.

QDRANT_DISK="/dev/disk/by-id/google-qdrant-data"
QDRANT_MOUNT="/mnt/qdrant-data"

# Wait up to 30 s for the disk symlink to materialise after boot
for i in $(seq 1 30); do
  [ -e "$QDRANT_DISK" ] && break
  echo "Waiting for Qdrant disk ($i/30)..."
  sleep 1
done
[ -e "$QDRANT_DISK" ] || { echo "ERROR: Qdrant disk not found after 30 s"; exit 1; }

# Format only if no filesystem exists (first boot only)
if ! blkid "$QDRANT_DISK" &>/dev/null; then
  echo "First boot: formatting Qdrant disk as ext4"
  mkfs.ext4 -F "$QDRANT_DISK"
fi

mkdir -p "$QDRANT_MOUNT"

# Mount only if not already mounted (fstab handles subsequent boots)
if ! mountpoint -q "$QDRANT_MOUNT"; then
  mount "$QDRANT_DISK" "$QDRANT_MOUNT"
fi

# Persist in fstab so systemd auto-mounts on reboot (idempotent)
if ! grep -q "google-qdrant-data" /etc/fstab; then
  echo "/dev/disk/by-id/google-qdrant-data $QDRANT_MOUNT ext4 defaults,nofail 0 2" >> /etc/fstab
fi

# Qdrant container runs as UID 1000 (qdrant user in official image)
chown 1000:1000 "$QDRANT_MOUNT"
chmod 750 "$QDRANT_MOUNT"

# ── Resolve worker image tag ──────────────────────────────────────────────────
# CI/CD writes the deployed SHA to instance metadata (worker-image-tag) so that
# the image can be updated without replacing the VM via `terraform apply`.
# Falls back to the tag baked in by Terraform at `apply` time if not set.

IMAGE_TAG=$(meta "instance/attributes/worker-image-tag" 2>/dev/null || true)
if [ -z "$IMAGE_TAG" ]; then
  IMAGE_TAG="${image_tag}"
fi

# ── Fetch secrets from Secret Manager ────────────────────────────────────────

get_secret() {
  gcloud secrets versions access latest --secret="$1" --project="$PROJECT_ID"
}

REDIS_PASSWORD=$(get_secret "${redis_password_secret_id_short}")
DB_PASSWORD=$(get_secret "${db_password_secret_id_short}")
API_SECRET_KEY=$(get_secret "${api_secret_key_secret_id_short}")
ANTHROPIC_API_KEY=$(get_secret "${anthropic_key_secret_id_short}")
OPENAI_API_KEY=$(get_secret "${openai_key_secret_id_short}")

# ── Authenticate Docker to Artifact Registry ──────────────────────────────────

gcloud auth configure-docker ${registry_hostname} --quiet

# ── Write runtime .env (chmod 600 — root read only) ──────────────────────────

mkdir -p /opt/forensic-flight

cat > /opt/forensic-flight/.env <<EOF
# Generated by startup script on every boot — do not edit manually
ENV=prod
LOG_LEVEL=INFO

# Database
DATABASE_URL=postgresql+asyncpg://forensic_flight:$${DB_PASSWORD}@${db_host}:5432/${db_name}
DATABASE_URL_SYNC=postgresql+psycopg2://forensic_flight:$${DB_PASSWORD}@${db_host}:5432/${db_name}

# Redis
# Workers reach Redis via container name (docker bridge).
# Cloud Run reaches Redis via VM internal IP.
REDIS_HOST=$${VM_INTERNAL_IP}
REDIS_PORT=6379
REDIS_PASSWORD=$${REDIS_PASSWORD}
CELERY_BROKER_URL=redis://:$${REDIS_PASSWORD}@redis:6379/0
CELERY_RESULT_BACKEND=redis://:$${REDIS_PASSWORD}@redis:6379/1

# Qdrant — container name, reachable within docker bridge only
QDRANT_URL=http://qdrant:6333

# GCS
GCS_DATA_BUCKET=${gcs_data_bucket}

# LLM — inference routing
INFERENCE_MODE=api
CRITICAL_PROVIDER=anthropic
CRITICAL_MODEL=claude-haiku-4-5-20251001
DOMAIN_PROVIDER=openai
DOMAIN_MODEL=gpt-4o-mini-2024-07-18
FALLBACK_PROVIDER=anthropic
FALLBACK_MODEL=claude-haiku-4-5-20251001
EMBEDDING_PROVIDER=openai
ANTHROPIC_API_KEY=$${ANTHROPIC_API_KEY}
OPENAI_API_KEY=$${OPENAI_API_KEY}

# App
SECRET_KEY=$${API_SECRET_KEY}
EOF

chmod 600 /opt/forensic-flight/.env

# ── Write docker-compose.yml ──────────────────────────────────────────────────

cat > /opt/forensic-flight/docker-compose.yml <<COMPOSE
version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: >
      redis-server
        --requirepass "$${REDIS_PASSWORD}"
        --maxmemory 512mb
        --maxmemory-policy allkeys-lru
        --save ""
    ports:
      - "$${VM_INTERNAL_IP}:6379:6379"
    networks:
      - internal

  qdrant:
    image: qdrant/qdrant:v1.8.4
    restart: unless-stopped
    ports:
      - "127.0.0.1:6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - internal

  worker-parse:
    image: ${registry_hostname}/${registry_repo}/worker:$IMAGE_TAG
    restart: unless-stopped
    command: celery -A api.workers.celery_app worker -Q parse -c 2 --loglevel=INFO
    env_file: .env
    depends_on:
      - redis
      - qdrant
    networks:
      - internal

  worker-investigate:
    image: ${registry_hostname}/${registry_repo}/worker:$IMAGE_TAG
    restart: unless-stopped
    command: celery -A api.workers.celery_app worker -Q investigate -c 1 --loglevel=INFO
    env_file: .env
    depends_on:
      - redis
      - qdrant
    networks:
      - internal

volumes:
  qdrant_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $QDRANT_MOUNT

networks:
  internal:
    driver: bridge
COMPOSE

# H4: docker-compose.yml contains Redis password in command arg — restrict access
chmod 600 /opt/forensic-flight/docker-compose.yml

# ── systemd service ───────────────────────────────────────────────────────────

cat > /etc/systemd/system/forensic-flight.service <<UNIT
[Unit]
Description=Forensic Flight worker stack
Requires=docker.service
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/opt/forensic-flight
ExecStart=/usr/bin/docker compose up -d --pull always
ExecStop=/usr/bin/docker compose down
TimeoutStartSec=300
TimeoutStopSec=60

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable forensic-flight.service
systemctl restart forensic-flight.service

echo "Forensic Flight startup complete"
